apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hackathon-todo.secretName" . }}
  labels:
    {{- include "hackathon-todo.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  BETTER_AUTH_SECRET: {{ .Values.secrets.BETTER_AUTH_SECRET | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | quote }}
  OPENAI_BASE_URL: {{ .Values.secrets.OPENAI_BASE_URL | quote }}
